services:

  forward-auth:
    network_mode: host
    build:
      context: backend/forwardAuth
      dockerfile: Dockerfile
    image: forward-auth:v1
    restart: always
    env_file:
      - backend/forwardAuth/.env.dev
    volumes:
      - ./configs/certs:/certs:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.forward-auth.rule=Host(`api.evalio.click`)"
      - "traefik.http.routers.forward-auth.entrypoints=web"
      - "traefik.http.routers.forward-auth.service=forward-auth"
      - "traefik.http.services.forward-auth.loadbalancer.server.port=1337"
      - "traefik.http.routers.forward-auth.middlewares=forward-auth-cors"
      - "traefik.http.middlewares.forward-auth-cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE,PATCH"
      - "traefik.http.middlewares.forward-auth-cors.headers.accesscontrolallowheaders=Origin, Content-Type, Accept, Authorization, X-Requested-With, X-User-Id, X-User-Email"
      - "traefik.http.middlewares.forward-auth-cors.headers.accesscontrolalloworiginlist=http://localhost:5173,http://evalio.click,https://evalio.click,http://localhost:5000"
      - "traefik.http.middlewares.forward-auth-cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.forward-auth-cors.headers.addvaryheader=true"
      - "traefik.http.middlewares.forward-auth-cors.headers.accesscontrolallowcredentials=true"

  mongo:
    network_mode: host
    image: mongo:8.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: developer
      MONGO_INITDB_ROOT_PASSWORD: 89c2ff58768d4d2afaa137f8
    volumes:
      - ./volumes/mongo-data:/data/db

  nats:
    network_mode: host
    image: nats:2.11.3
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: [
      "-js",
      "-m", "8222",
      "--store_dir", "/data/jetstream"
    ]
    volumes:
      - ./volumes/nats-data:/data/jetstream

  minio:
    network_mode: host
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./volumes/minio-data:/data

  reverse-proxy:
    network_mode: host
    image: traefik:v3.4
    ports:
      # The HTTP port
      - "0.0.0.0:80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
      - "0.0.0.0:443:443"  # Puerto para HTTPS
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./volumes/certs:/etc/traefik/certs:ro  # Monta los certificados
      - ./traefik.yml:/etc/traefik/traefik.yml:ro


  evalio-manager:
    network_mode: host
    build:
      context: backend/admin
      dockerfile: Dockerfile
    image: evalio-manager:v1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.evalio-manager.rule=Host(`api.evalio.click`) && PathPrefix(`/manager`)"
      - "traefik.http.routers.evalio-manager.entrypoints=web"
      - "traefik.http.routers.evalio-manager.service=evalio-manager"
      - "traefik.http.services.evalio-manager.loadbalancer.server.port=8081"
      - "traefik.http.routers.evalio-manager.middlewares=forward-auth"
      - "traefik.http.middlewares.forward-auth.forwardauth.address=http://localhost:1337/auth"
      - "traefik.http.middlewares.forward-auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.forward-auth.forwardauth.authResponseHeaders=X-User-Id,X-User-Email"
      - "traefik.http.middlewares.testheader.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE,PATCH"
      - "traefik.http.middlewares.testheader.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.testheader.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.testheader.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.testheader.headers.addvaryheader=true"

    restart: always
    env_file:
      - backend/admin/admin/.env.dev
    volumes:
      - ./configs/certs:/certs:ro


  users-manager:
    network_mode: host
    build:
      context: backend/usersManager
      dockerfile: Dockerfile
    image: users-manager:v1
    restart: always
    env_file:
      - backend/usersManager/.env.dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.users-manager.rule=Host(`api.evalio.click`) && (PathPrefix(`/users-manager`) || PathPrefix(`/public`))"
      - "traefik.http.routers.users-manager.entrypoints=web"
      - "traefik.http.routers.users-manager.service=users-manager"
      - "traefik.http.services.users-manager.loadbalancer.server.port=3000"
      - "traefik.http.routers.users-manager.middlewares=forward-auth"
      - "traefik.http.middlewares.forward-auth.forwardauth.address=http://localhost:1337/auth"
      - "traefik.http.middlewares.forward-auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.forward-auth.forwardauth.authResponseHeaders=X-User-Id,X-User-Email"
      - "traefik.http.middlewares.testheader.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE,PATCH"
      - "traefik.http.middlewares.testheader.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.testheader.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.testheader.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.testheader.headers.addvaryheader=true"


    volumes:
      - ./configs/certs:/certs:ro

  # evalio-analyzer:
  #   network_mode: host
  #   build:
  #     context: backend/grader_analyzer
  #     dockerfile: Dockerfile
  #   image: cv-grader-analyzer:v1
  #   restart: always
  #   env_file:
  #     - backend/grader_analyzer/grader_analyzer/.env.dev


  # evalio-front:
  #   build:
  #     context: .
  #     dockerfile: apps/evalio-ui/Dockerfile
  #   image: evalio-ui:v1
  #   restart: always
  #   ports:
  #     - "5000:5000"
